name: Solidity contract tests
on: [push]
jobs:
  tests:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: "16.x"

      - name: node version
        run: node --version

      - name: contract - npm install
        run: npm install
        working-directory: ./contract

      - name: web-server - npm install - dependencies needed for utils module
        run: npm install
        working-directory: ./web-server

      - name: contract - test
        run: npm run test-ci
        working-directory: ./contract

  prettier:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - uses: actions/checkout@v2

    # run prettier, and also ensure any lock file changes are reverted
    - name: Prettify web-client
      run: yarn && yarn prettier && git restore yarn.lock
      working-directory: ./web-client

    # run prettier, and also ensure any lock file changes are reverted
    - name: Prettify web-server
      run: yarn && yarn prettier && git restore yarn.lock && git restore package-lock.json
      working-directory: ./web-server

    # run prettier, and also ensure any lock file changes are reverted
    - name: Prettify contract
      run: yarn && yarn prettier && git restore yarn.lock
      working-directory: ./contract

    # commit and push changes
    - name: Commit style fixes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Code style fixes
        commit_user_name: Github Action
